create table if not exists public.people (
  id bigint generated by default as identity primary key,
  public_code text not null unique,
  full_name text not null,
  address text not null,
  phone text not null,
  emergency_phone text,
  diagnosis_summary text,
  audio_path text,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists people_public_code_idx on public.people (public_code);

insert into storage.buckets (id, name, public)
select 'audio-recordings', 'audio-recordings', true
where not exists (
  select 1
  from storage.buckets
  where id = 'audio-recordings'
);

drop policy if exists "Public can read audio recordings" on storage.objects;
create policy "Public can read audio recordings"
on storage.objects
for select
to public
using (bucket_id = 'audio-recordings');
